version: "3"

volumes:
  mysql-data: {}
  redis-data: {}

services:
  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mailtrain
      - MYSQL_DATABASE=mailtrain
      - MYSQL_USER=mailtrain
      - MYSQL_PASSWORD=mailtrain
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  
  redis:
    image: redis
    volumes:
      - "redis-data:/data"
    restart: always

  mailtrain:
    image: tijlvdb/mailtrain:latest
    # build: container/
    depends_on:
      - mysql
      - redis
    volumes:
      - "./config/:/opt/config"
    ports:
      - "3000:80"
    links:
      - "mysql:mysql"
      - "redis:redis"
    restart: always